/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibraryIdRouteImport } from './routes/library.$id'
import { Route as ApiPan115ImgRouteImport } from './routes/api/pan115/img'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRoute,
} as any)
const LibraryIdRoute = LibraryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LibraryRoute,
} as any)
const ApiPan115ImgRoute = ApiPan115ImgRouteImport.update({
  id: '/api/pan115/img',
  path: '/api/pan115/img',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRouteWithChildren
  '/models': typeof ModelsRoute
  '/pipeline': typeof PipelineRoute
  '/sources': typeof SourcesRoute
  '/workflow': typeof WorkflowRoute
  '/library/$id': typeof LibraryIdRoute
  '/library/': typeof LibraryIndexRoute
  '/api/pan115/img': typeof ApiPan115ImgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/models': typeof ModelsRoute
  '/pipeline': typeof PipelineRoute
  '/sources': typeof SourcesRoute
  '/workflow': typeof WorkflowRoute
  '/library/$id': typeof LibraryIdRoute
  '/library': typeof LibraryIndexRoute
  '/api/pan115/img': typeof ApiPan115ImgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRouteWithChildren
  '/models': typeof ModelsRoute
  '/pipeline': typeof PipelineRoute
  '/sources': typeof SourcesRoute
  '/workflow': typeof WorkflowRoute
  '/library/$id': typeof LibraryIdRoute
  '/library/': typeof LibraryIndexRoute
  '/api/pan115/img': typeof ApiPan115ImgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/models'
    | '/pipeline'
    | '/sources'
    | '/workflow'
    | '/library/$id'
    | '/library/'
    | '/api/pan115/img'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/models'
    | '/pipeline'
    | '/sources'
    | '/workflow'
    | '/library/$id'
    | '/library'
    | '/api/pan115/img'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/models'
    | '/pipeline'
    | '/sources'
    | '/workflow'
    | '/library/$id'
    | '/library/'
    | '/api/pan115/img'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRouteWithChildren
  ModelsRoute: typeof ModelsRoute
  PipelineRoute: typeof PipelineRoute
  SourcesRoute: typeof SourcesRoute
  WorkflowRoute: typeof WorkflowRoute
  ApiPan115ImgRoute: typeof ApiPan115ImgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/$id': {
      id: '/library/$id'
      path: '/$id'
      fullPath: '/library/$id'
      preLoaderRoute: typeof LibraryIdRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/api/pan115/img': {
      id: '/api/pan115/img'
      path: '/api/pan115/img'
      fullPath: '/api/pan115/img'
      preLoaderRoute: typeof ApiPan115ImgRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LibraryRouteChildren {
  LibraryIdRoute: typeof LibraryIdRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryIdRoute: LibraryIdRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRouteWithChildren,
  ModelsRoute: ModelsRoute,
  PipelineRoute: PipelineRoute,
  SourcesRoute: SourcesRoute,
  WorkflowRoute: WorkflowRoute,
  ApiPan115ImgRoute: ApiPan115ImgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
